"""
Chatbot RAG Route — Main AI assistant endpoint.
Orchestrates dialog, intent detection, RAG retrieval, and CendolNLP response generation.
Supports all modules: Dry Run, Nego Coach, Smart Calendar, Post-Export Solver, and general QA.
"""
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from app.middleware import get_current_user, get_optional_user
from app.services.rag_service import query_regulations, generate_rag_response
from app.services.cendol_service import CendolNLPService
import logging

logger = logging.getLogger(__name__)

router = APIRouter()


class ChatRequest(BaseModel):
    message: str
    context_data: dict = {}


class ChatResponse(BaseModel):
    reply: str
    detected_intent: str
    referenced_sources: str
    # AI Transparency metadata
    ai_metadata: Dict[str, Any] = {}
    inference_id: str = ""


@router.post("/send", response_model=ChatResponse)
def process_chat(req: ChatRequest, current_user: dict = Depends(get_optional_user)):
    """
    Main chatbot endpoint. Processes user messages through:
    1. Intent classification
    2. RAG context retrieval from ChromaDB
    3. Response generation via CendolNLP (with fallback)
    4. Returns AI transparency metadata alongside the answer
    """
    try:
        user_message = req.message

        # 1. Classify intent
        intent = CendolNLPService.classify_intent(user_message)

        # 2. Retrieve local RAG context
        from app.services.vector_store import query_regulations
        rag_context = query_regulations(user_message)

        # 3. Generate response with RAG + Live Search Grounding
        result = CendolNLPService.generate_response(
            user_message, context=rag_context, module="chat"
        )

        # Extract answer and metadata from result dict
        reply = result.get("answer", "")
        ai_metadata = {k: v for k, v in result.items() if k != "answer"}
        inference_id = result.get("inference_id", "")

        # 4. Dynamic official clickable source links (Prioritize Gemini Search Grounding & Gemini-generated links)
        grounding_sources = result.get("grounding_sources", [])
        
        # Also extract in-text markdown links generated by Gemini
        import re
        in_text_links = re.findall(r"\[([^\]]+)\]\((https?://[^\)]+)\)", reply)
        for title, u in in_text_links:
            if not any(g.get("url") == u for g in grounding_sources):
                grounding_sources.append({"title": title.strip(), "url": u.strip()})

        if grounding_sources:
            seen = set()
            unique_sources = []
            for s in grounding_sources:
                u = s.get("url", "")
                if u and u not in seen:
                    seen.add(u)
                    title = s.get("title", "Sumber Web")
                    unique_sources.append(f"[{title}]({u})")
            sources = " | ".join(unique_sources[:6]) if unique_sources else _get_official_sources(intent, user_message)
        else:
            sources = _get_official_sources(intent, user_message)

        return ChatResponse(
            reply=reply,
            detected_intent=intent,
            referenced_sources=sources,
            ai_metadata=ai_metadata,
            inference_id=inference_id,
        )

    except Exception as e:
        logger.error(f"Chat error: {e}")
        return ChatResponse(
            reply="Maaf, terjadi gangguan sementara. Silakan coba lagi atau reformulasi pertanyaan Anda.",
            detected_intent="error",
            referenced_sources="[Portal INSW](https://insw.go.id) | [Kemendag RI](https://kemendag.go.id)",
            ai_metadata={"ai_tier": "error", "confidence": 0.0},
            inference_id="",
        )


def _get_official_sources(intent: str, text: str) -> str:
    """Return tailored clickable Markdown links to official trade portals based on query context."""
    t = text.lower()
    
    # Specific destination country portals
    if any(k in t for k in ["jepang", "japan", "tokyo"]):
        return "[JETRO Japan Regulations](https://www.jetro.go.jp/en/reports/regulations/) | [Japan MHLW Food Sanitation](https://www.mhlw.go.jp/english/) | [IJEPA Kemendag](https://ditjenppi.kemendag.go.id) | [Portal INSW](https://insw.go.id)"
    elif any(k in t for k in ["amerika", "usa", "us", "united states"]):
        return "[US FDA Food Safety](https://www.fda.gov/food) | [US Customs CBP](https://www.cbp.gov) | [InaExport Kemendag](https://inaexport.id) | [Portal INSW](https://insw.go.id)"
    elif any(k in t for k in ["eropa", "jerman", "belanda", "prancis", "italia", "eu", "europe"]):
        return "[EU Access2Markets Helpdesk](https://trade.ec.europa.eu/access-to-markets/) | [European Food Safety Authority](https://www.efsa.europa.eu) | [Portal INSW](https://insw.go.id)"
    elif any(k in t for k in ["china", "tiongkok"]):
        return "[GACC China CIFER](https://cifer.singlewindow.cn) | [ACFTA Kemendag](https://ditjenppi.kemendag.go.id) | [Portal INSW](https://insw.go.id)"
    elif any(k in t for k in ["arab", "saudi", "timur tengah", "uae", "dubai"]):
        return "[SFDA Saudi Arabia](https://www.sfda.gov.sa/en) | [BPJPH Halal Indonesia](https://halal.go.id) | [InaExport](https://inaexport.id)"
    elif any(k in t for k in ["australia", "sydney", "melbourne"]):
        return "[Australia DAFF Biosecurity](https://www.agriculture.gov.au/biosecurity-trade) | [IA-CEPA Kemendag](https://ditjenppi.kemendag.go.id) | [Portal INSW](https://insw.go.id)"
    
    # Specific commodity & topic rules
    if any(k in t for k in ["hs code", "tarif", "bea", "cukai", "peb", "pabean"]):
        return "[Portal INSW](https://insw.go.id) | [Bea Cukai RI](https://customs.go.id) | [Kemenkeu BTKI](https://bctemas.beacukai.go.id)"
    elif any(k in t for k in ["pasar", "market", "peluang", "comtrade", "gap", "impor"]):
        return "[UN COMTRADE Database](https://comtradeplus.un.org) | [InaExport Kemendag](https://inaexport.id) | [Kementerian Perdagangan](https://kemendag.go.id)"
    elif any(k in t for k in ["bpom", "makanan", "tempe", "keripik", "kopi", "snack", "halal", "karantina"]):
        return "[BPOM RI Registrasi Pangan](https://pom.go.id) | [BPJPH Halal](https://halal.go.id) | [Portal INSW](https://insw.go.id) | [InaExport](https://inaexport.id)"
    elif any(k in t for k in ["rcep", "ijepa", "acfta", "fta", "ska", "form e", "form d"]):
        return "[Portal SKA Kemendag](https://e-ska.kemendag.go.id) | [Perjanjian Dagang RI](https://ditjenppi.kemendag.go.id) | [INSW Portal](https://insw.go.id)"
    else:
        return "[Portal INSW](https://insw.go.id) | [Kementerian Perdagangan RI](https://kemendag.go.id) | [InaExport](https://inaexport.id) | [Bea Cukai RI](https://customs.go.id)"
